// <auto-generated />
using System;
using CognizantChallenge.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CognizantChallenge.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CognizantChallenge.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("614f97de-6131-4a30-84c0-caf32aec4dad"),
                            Description = "Write a program that prints at least 10 members of the Fibonacci sequence, the starting input will be in following format: 2,3",
                            Input = "2,3",
                            Output = "5 8 13 21 34 55 89 144 233 377",
                            TaskName = "Fibonacci series"
                        },
                        new
                        {
                            Id = new Guid("1365247a-c078-453f-b378-83a1750e27c3"),
                            Description = "You have a collection of integers, 1 to 30. I want you to cycle through this collection. For each number found that is evenly divisible by 3, output the word 'Fizz'. For each number that is evenly divisible by 5, output the word 'Buzz'. For each number that is evenly divisible by both 3 AND 5, output the word 'FizzBuzz'.",
                            Input = "",
                            Output = "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz 16 17 Fizz 19 Buzz Fizz 22 23 Fizz Buzz 26 Fizz 28 29 FizzBuzz",
                            TaskName = "FizzBuzz"
                        },
                        new
                        {
                            Id = new Guid("62b2866f-fec4-46b5-85cb-f5d4832a4477"),
                            Description = "Write a program that prints at least 25 first prime numbers. Prime number is a number that is greater than 1 and divided by 1 or itself. In other words, prime numbers can't be divided by other numbers than itself or 1.",
                            Input = "",
                            Output = "2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 83 89 97",
                            TaskName = "Prime numbers"
                        },
                        new
                        {
                            Id = new Guid("b644f15c-b2c6-44cd-9304-2ca09697bc66"),
                            Description = "Write a C# Sharp program that takes four numbers as input to calculate and print the average. The input numbers will be in following format: 10,15,20,30",
                            Input = "10,15,20,30",
                            Output = "18",
                            TaskName = "Average numbers"
                        });
                });

            modelBuilder.Entity("CognizantChallenge.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskEntityUserEntity", b =>
                {
                    b.Property<Guid>("SolvedTasksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolvedTasksId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("TaskEntityUserEntity", b =>
                {
                    b.HasOne("CognizantChallenge.Domain.Entities.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("SolvedTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CognizantChallenge.Domain.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
